### ISSUE TITLE
custom ORM model manager

### ISSUE THREAD

**Issue by v-popovski** [Aerendir/bundle-aws-ses-monitor#21]
Two issues when working with a custom entity manager:

In:  *aws-ses-monitor-bundle/Command/SnsSetupCommandAbstract.php*

line 90 needs to be changed from: 
$this->getContainer()->get('doctrine.orm.default_entity_manager')->flush();

to:
$this->getContainer()->get(**'aws_ses_monitor.entity_manager'**)->flush();

and line 181 from:
$this->getContainer()->get('doctrine.orm.default_entity_manager')->persist($topic);

to:
$this->getContainer()->get(**'aws_ses_monitor.entity_manager'**)->persist($topic);

Thanks!

**Comment by Aerendir** [comment]
Can you send a PR for this?
