### ISSUE TITLE
Email statuses duplicated entry

### ISSUE THREAD

**Issue by dextervip** [Aerendir/bundle-aws-ses-monitor#26]
Hey, 

I have been getting few exceptions about duplicate entry in email statuses table. Any ideas?

`An exception occurred while executing 'INSERT INTO aws_ses_monitor_email_statuses (hard_bounces_count, soft_bounces_count, last_bounce_type, last_time_bounced, complaints_count, last_time_complained, deliveries_count, last_time_delivered, email_address) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [0, 0, null, null, 0, null, 1, "2017-08-21 11:01:16", "xxxxx@xxx.com.br"]: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "aws_ses_monitor_email_statuses_pkey" DETALHE: Key (email_address)=(xxxxx@xxx.com.br) already exists.`

I am running Sf 2.8 with "serendipity_hq/aws-ses-monitor-bundle": "^1.2"

**Comment by Aerendir** [comment]
Can you give some more context to try to reproduce the issue?

It seems it is trying to create the email in the table instead of updating the existent one...

If you can give more context I'll try to fix the issue.

**Comment by jonny-no1** [comment]
Same in Symfony 3.3. Haven't got round to investigate, but will hopefully find time soon.

**Comment by Aerendir** [comment]
The problem is caused by the fact that somewhere in the code the email is not intercepted as existent but instead is treated as a new one.

So the bundle try to create the email and this causes the error.

If both of you can provide more context I'll fix this.

**Comment by jonny-no1** [comment]
Thanks @Aerendir! I reckon I'll find time to write a test that describes the bug this week.

**Comment by jonny-no1** [comment]
Not sure this will be useful as I removed the Request log entry to protect the sensitive information it contains: https://jsfiddle.net/mpsgu9e4/show/
