### ISSUE TITLE
Dispatch some events

### ISSUE THREAD

**Issue by dextervip** [Aerendir/bundle-aws-ses-monitor#31]
Hey,

It would be nice to dispatch some events about bounces, complaints so that we can subscribe to make extra treatments in our app.

Regards

**Comment by Aerendir** [comment]
Hi @dextervip , this is a good idea...

In some days I will update the bundle to make it better, adding some new functionalities and generally improving the code.

I'd appreciate a lot if you could expand this suggestion with some use cases you like to get covered, so I can implement a better event system...

**Comment by dextervip** [comment]
Well my case use would be to listen events when emails are hard bounced and update my customer personal info entity to flag this email as invalid so my system stops sending and my agents know this is an invalid contact.

**Comment by Aerendir** [comment]
Ok, I understand your point...

I'm deeply refactoring the bundle and adding new features: this will be added in the version 2.0.

I hope in a couple of weeks to finish...

**Comment by Aerendir** [comment]
Tracked by https://github.com/Aerendir/aws-ses-monitor-bundle/issues/64 to make GitHub able to calculate the progress.

**Comment by dextervip** [comment]
Awesome! At moment, as a workaround I had to override the entire handle class (all methods are private so i couldn't override the specific method I needed, idk maybe refactor to protected would be good also).

**Comment by Aerendir** [comment]
@dextervip , I've completely refactored the handlers: check the new code that should be more clear to understand.

Start from the `EndpointController` and it will guide you down towards the handlers...

Any feedback about the new code is welcome!

**Comment by drzraf** [comment]
Hi,
I've the same need. There like a blackhole in the documentation after "_4. Test-dev.md_", because "_5. Using_" is only about "collected" information and not reacting to endpoint requests.

I would expect to process the bounces notifications in real time and, for that, having a controller somehow listening to these events. I can't find examples of this.

**Comment by Aerendir** [comment]
@drzraf, the events are not fired in this moment.

I deeply refactored the bundle and introduced a completely revamped command to configure the app with AWS SES.

I plan to add the events in the next minor version.

Any help on this, anyway, will be welcome!

The main issue for this is this https://github.com/Aerendir/aws-ses-monitor-bundle/issues/64

I plan to add at least 5 events. More info in the linked issue.

**Comment by Aerendir** [comment]
PS The documentation is not still updated: I'm updating it...
