### ISSUE TITLE
Add Open/Click events

### ISSUE THREAD

**Issue by malas** [Aerendir/bundle-aws-ses-monitor#84]
`NotificationProcessor.php` should also process the open and click Notifications from AWS and dispatch corresponding symfony events.

Ping #64

**Comment by Aerendir** [comment]
Hi @malas , thank you for highlighting this!

I'm in the process of better understanding how the system works and how to implement it.

This is not as simple as reading the responses from Amazon, but requires to think also at the way the bundle handles the configuration of topics.

Without speaking about GDPR, that for sure is not something that the bundle should take into account. But, as the bundle will make a lot easier to configure the tracking features, a mention, also if very small, should be done.

Are you able to implement this feature?

**Comment by malas** [comment]
After examining your bundle we have decided to roll our own solution.

The main difference is that our solution will only emit a coresponding symfony event on SNS notification an then one can hook any logic he wants.

**Comment by Aerendir** [comment]
Ok, as you like.

Just to understand better, if you like to answer me: currently, the bundle doesn't emit any event: this is a planned feature that will be released very soon.

Once the bundle will emit the Symfony events, which will be the difference with your own solution?

**Comment by malas** [comment]
Our solution will not have any additional logic bundled within like saving
smth to database.

Our viewpoint is to do one thing and do it very well. In this case it would
be to receive and parse sns rmail notifications.

**Comment by Aerendir** [comment]
Ok, I understand your point. Anyway, thank you for your comment :)
